site_name: DIY Spectrometer Documentation
theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - navigation.tracking
    - search.highlight
    - search.suggest

# This tells MkDocs where to find your files
docs_dir: Docs

# 1. Enable the math extension
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

# 2. Link the MathJax library to render the symbols
extra_javascript:
  - Pages/javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  
nav:
  - Introduction and Objectives: Pages/index.md
  - Theoretical Background: Pages/theory.md
  - Review of Low-Cost / DIY Spectrophotometers: Pages/review.md
  - Design and Implementation of the Spectrophotometer: Pages/implementation.md
  - Error Analysis and Limitations: Pages/errors.md
  - Conclusion: Pages/conclusion.md
  - Bibliography: Pages/bibliography.md
#  - Java Documentation: JavaDocs/index.html
