site_name: DIY Spectrometer Documentation
theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - navigation.tracking
    - search.highlight
    - search.suggest

# This tells MkDocs where to find your files
docs_dir: Docs/Pages

nav:
  - Introduction and Objectives: index.md
  - Theoretical Background: theory.md
  - Review of Low-Cost / DIY Spectrophotometers: review.md
  - Design and Implementation of the Spectrophotometer: implementation.md
  - Error Analysis and Limitations: errors.md
  - Conclusion: conclusion.md
  - Bibliography: bibliography.md
